asset:
- changed-files:
  - any-glob-to-any-file: 'public/**'
ci:
- changed-files:
  - any-glob-to-any-file: '.github/**/*.yml'
config:
- changed-files:
  - any-glob-to-any-file: '*config.*'
content:
- changed-files:
  - any-glob-to-any-file: 'app/**'
dependencies:
- changed-files:
  - any-glob-to-any-file: ['bun.lockb', 'package.json', 'yarn.lock']
docker:
- changed-files:
  - any-glob-to-any-file: ['.dockerignore', 'Dockerfile']
documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'
enhancement:
 - head-branch: ['^feature', 'feature', '^enhancement', 'enhancement']
git:
- changed-files:
  - any-glob-to-any-file: ['.gitattributes', '.gitignore']
infrastructure:
- changed-files:
  - any-glob-to-any-file: ['.devcontainer/*', '.editorconfig', 'biome.json']
vscode:
- changed-files:
  - any-glob-to-any-file: '.vscode/*'
