changelog:
  categories:
    - title: 🚀 Exciting New Features
      labels:
        - content
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 📖 Documentation
      labels:
        - documentation
    - title: 🆙 Version Up
      labels:
        - dependencies
    - title: 🧰 Maintenance
      labels:
        - "*"
