name: 🐛 Bug Report
description: File a bug report
title: "🐛 [Bug]: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report🤗

        If you need help or support, and are not reporting a bug, please join our
        [Discord](https://discord.gg/tSHMqK8VDU) server, where you can ask questions in the [`#help`](https://discord.gg/bYA8kWPEg4) forum.

        Make sure you are running the latest version.
        The bug you are experiencing may already have been fixed.

        Please try to include as much information as possible.
  - type: input
    id: version
    attributes:
      label: 🔍 Version
      description: What version of our software are you running?
      placeholder: ex. v0.1.0
  - type: textarea
    id: what-happened
    attributes:
      label: 👀 What happened?
      description: A clear and concise description of what you need assistance with.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 🎋 What is the expected behavior?
      description: If possible, please provide text with a screenshot.
  - type: dropdown
    id: browsers
    attributes:
      label: 🌐 What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: additional-info
    attributes:
      label: 📝 Additional information
      description: Is there anything else you think we should know?
  - type: checkboxes
    id: terms
    attributes:
      label: ⚖️ Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/OpenUp-LabTakizawa/ckt-liff-app/blob/main/CONTRIBUTING.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
