name: Docker Hub CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
    paths:
      - "app/**"
      - "public/**"
      - "next.config.js"
      - "package.json"
      - "postcss.config.js"
      - "tailwind.config.ts"
      - "tsconfig.json"
      - "yarn.lock"
  pull_request_target:
    branches: [ main ]
    paths:
      - "app/**"
      - "public/**"
      - "next.config.js"
      - "package.json"
      - "postcss.config.js"
      - "tailwind.config.ts"
      - "tsconfig.json"
      - "yarn.lock"
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: marukome0743/ckt-liff-app

jobs:
  build:
    name: push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: github.repository_owner == 'OpenUp-LabTakizawa'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.repository_owner == 'OpenUp-LabTakizawa' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=ckt-liff-app multi-arch image
          provenance: false

      - name: Docker Scout
        if: github.event_name == 'pull_request_target' && github.repository_owner == 'OpenUp-LabTakizawa'
        uses: docker/scout-action@v1
        with:
          command: compare
          image: ${{ steps.meta.outputs.tags }}
          to: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ignore-unchanged: true
          only-severities: critical,high
          write-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
