name: Docker CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
    paths:
      - "app/**"
      - "public/**"
      - "next.config.js"
      - "package.json"
      - "postcss.config.js"
      - "tailwind.config.ts"
      - "tsconfig.json"
      - "yarn.lock"
  pull_request_target:
    branches: [ main ]
    paths:
      - "app/**"
      - "public/**"
      - "next.config.js"
      - "package.json"
      - "postcss.config.js"
      - "tailwind.config.ts"
      - "tsconfig.json"
      - "yarn.lock"
  workflow_dispatch:

env:
  REPOSITORY_OWNER: OpenUp-LabTakizawa
  REGISTRY: docker.io
  REPOSITORY: marukome0743/ckt-liff-app
  GHCR_REGISTRY: ghcr.io
  GHCR_REPOSITORY: openup-labtakizawa/ckt-liff-app

jobs:
  build:
    name: docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: github.repository_owner == env.REPOSITORY_OWNER
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
      - name: Login to GitHub Container Registry
        if: github.repository_owner == env.REPOSITORY_OWNER
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.REPOSITORY }}
            ${{ env.GHCR_REGISTRY }}/${{ env.GHCR_REPOSITORY }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.repository_owner == env.REPOSITORY_OWNER }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REPOSITORY }}:main
          cache-to: type=inline
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=ckt-liff-app multi-arch image
          provenance: false
      - name: Docker Scout
        if: github.repository_owner == env.REPOSITORY_OWNER && github.event_name == 'pull_request_target'
        uses: docker/scout-action@v1
        with:
          command: compare
          image: ${{ env.REPOSITORY }}:${{ steps.meta.outputs.version }}
          to: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
          only-severities: critical,high
